/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend.components;

import Backend.DBController;
import Frontend.Admin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author canti
 */
public class ViewAcc extends javax.swing.JPanel {
    String myId;
    String myRole;
    String myName;
    Admin ref;
    /**
     * Creates new form ViewAcc
     */
    public ViewAcc(String myId, String myName, String myRole, Admin ref) {
        this.myId = myId;
        this.myName = myName;
        this.myRole = myRole;
        this.ref = ref;
        initComponents();
        apply.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editUsername = new javax.swing.JTextField(myName);
        editRole = new javax.swing.JTextField(myRole);
        jPanel1 = new javax.swing.JPanel();
        apply = new Frontend.components.MyButton();
        dlt = new Frontend.components.MyButton();
        edt = new Frontend.components.MyButton();

        setBackground(new java.awt.Color(50, 62, 143));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        setMaximumSize(new java.awt.Dimension(793, 75));
        setMinimumSize(new java.awt.Dimension(793, 75));
        setPreferredSize(new java.awt.Dimension(793, 75));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID: " + myId);

        editUsername.setEditable(false);
        editUsername.setBackground(new java.awt.Color(50, 62, 143));
        editUsername.setForeground(new java.awt.Color(255, 255, 255));
        editUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        editRole.setEditable(false);
        editRole.setBackground(new java.awt.Color(50, 62, 143));
        editRole.setForeground(new java.awt.Color(255, 255, 255));
        editRole.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Role", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        editRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoleActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 62, 143));

        apply.setBackground(new java.awt.Color(102, 255, 102));
        apply.setForeground(new java.awt.Color(0, 0, 0));
        apply.setText("Apply");
        apply.setBase(new java.awt.Color(102, 255, 102));
        apply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apply.setRadius(12);
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        dlt.setForeground(new java.awt.Color(0, 0, 0));
        dlt.setText("Delete");
        dlt.setBase(new java.awt.Color(255, 51, 51));
        dlt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dlt.setHover(new java.awt.Color(153, 0, 0));
        dlt.setRadius(12);
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });

        edt.setForeground(new java.awt.Color(0, 0, 0));
        edt.setText("Edit");
        edt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edt.setHover(new java.awt.Color(153, 153, 153));
        edt.setRadius(12);
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dlt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(editUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(editRole, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        dlt.setEnabled(false);
        editUsername.setEditable(true);
        editRole.setEditable(true);
        apply.setVisible(true);
    }//GEN-LAST:event_edtActionPerformed

    private void editRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRoleActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        try (DBController dbc = new DBController()) {
            dbc.deleteUserById(Integer.parseInt(myId));
            ref.showAccounts();
        } catch (SQLException ex) {
            Logger.getLogger(ViewAcc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dltActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        try (DBController dbc = new DBController()) {
            int newRole = 1;
            if("admin".equalsIgnoreCase(editRole.getText())){
                newRole = 0;
            }
            dbc.updateUser(Integer.parseInt(myId), editUsername.getText(), newRole);
        } catch (SQLException ex) {
            Logger.getLogger(ViewAcc.class.getName()).log(Level.SEVERE, null, ex);
        }
        apply.setVisible(false);
        dlt.setEnabled(true);
    }//GEN-LAST:event_applyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Frontend.components.MyButton apply;
    private Frontend.components.MyButton dlt;
    private javax.swing.JTextField editRole;
    private javax.swing.JTextField editUsername;
    private Frontend.components.MyButton edt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
